//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LectoresAA.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Capitulo
    {
        public Capitulo()
        {
            this.Comentarios = new HashSet<Comentario>();
        }
    
        public int Id { get; set; }
        public string Titulo { get; set; }
        public string Fecha { get; set; }
        public string Contenido { get; set; }
        public int PublicacionId { get; set; }
    
        public virtual Publicacion Publicacion { get; set; }
        public virtual ICollection<Comentario> Comentarios { get; set; }
    }
}
