//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LectoresAA.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Publicacion
    {
        public Publicacion()
        {
            this.Capitulos = new HashSet<Capitulo>();
        }
    
        public int Id { get; set; }
        public string Autor { get; set; }
        public string Titulo { get; set; }
        public string Descripcion { get; set; }
        public string Fecha { get; set; }
        public string User { get; set; }
        public int TipoId { get; set; }
    
        public virtual Tipo Tipo { get; set; }
        public virtual ICollection<Capitulo> Capitulos { get; set; }
    }
}
